name: Notify on Push and Pull Request

on:
  push:
    branches:
      - main  # Replace with your branch name
  pull_request:
    branches:
      - main  # Replace with your branch name

jobs:
  send_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get commit message
        id: commit
        run: echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Send notification
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_USER_ID }}  # Replace with your Telegram user ID
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Replace with your Telegram bot token
          message: |
            Repository: ${{ github.repository }}
            Event: ${{ github.event_name }}
            Ref: ${{ github.ref }}
            Commit Message: ${{ steps.commit.outputs.message }}
